name: backup github
on:
  workflow_dispatch:

env:
  S3_BUCKET: classdojo-github-backup
  AWS_REGION: us-east-1
      
jobs:
  do_stuff:
    runs-on: ["self-hosted", "github-backup"]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Run
        run: |
          go run main.go ./bin/ghbackup
